steps:
  - name: "node:10.15.1"
    entrypoint: "yarn"
    args: ["install"]

  - name: "node:10.15.1"
    entrypoint: "yarn"
    args: ["build"]
    id: "build"

  - name: "docker/compose:1.24.1"
    # Add '-d' flag so Docker exits as soon as the container's been created and
    # we can go to the next step (which will wait for the server to become
    # available). Without this flag the command wouldn't exit until it was
    # manually killed...which will never happen in CI, obvi
    args: ["up", "datastore-emulator"]
    waitFor: ["build"]

    # TODO The `test:e2e` script runs `yarn build` which we've already run in a
    # previous step. That's a little wasteful?
  - name: "node:10.15.1"
    entrypoint: "yarn"
    args: ["test:e2e"]
    id: "test:e2e"
    waitFor: ["build"]

  - name: "node:10.15.1"
    entrypoint: "yarn"
    args: ["test:integration"]
    id: "test:integration"
    waitFor: ["test:e2e"]

    # Stop/destroy the datastore emulator that was started a few steps earlier
  - name: "docker/compose:1.24.1"
    args: ["down"]
    waitFor: ["test:integration"]
