steps:
  - name: "node:10.15.1"
    entrypoint: "yarn"
    args: ["install"]

  - name: "node:10.15.1"
    entrypoint: "yarn"
    args: ["build"]

  - name: "docker/compose:1.24.1"
    entrypoint: "/bin/sh"
    args:
      [
        "-c",
        "docker-compose up -d datastore-emulator && docker-compose run app yarn test:e2e",
      ]

    # TODO The `test:e2e` script runs `yarn build` which we've already run in a
    # previous step. That's a little wasteful?
  # - name: "node:10.15.1"
  #   entrypoint: "yarn"
  #   args: ["test:e2e"]

  - name: "node:10.15.1"
    entrypoint: "yarn"
    args: ["test:integration"]

    # Stop/destroy the datastore emulator that was started a few steps earlier
  - name: "docker/compose:1.24.1"
    args: ["down"]
