version: "3"

services:
  datastore-emulator:
    image: singularities/datastore-emulator
    # volumes:
    #   - firestore-data:/opt/data
    env_file:
      - ./docker-datastore-emulator.env
    ports:
      - "8080:8080"
    # Disable writing data to disk - this emulator is only for tests/dev,
    # writing to disk will just slow us down
    command: "--no-store-on-disk"
  app:
    image: node:10.15.1
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
